name: Publish contracts addresses

on:
  push:
    paths:
      - 'packages/contracts/genesis/**'
  workflow_dispatch:

jobs:
  publish-contract-address:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_DEV }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
        AWS_REGION: 'ap-northeast-2'
        SOURCE_DIR: 'packages/contracts/genesis'
